---
title: "MiMb Chapter"
output: html_document
---
```{r}
#libraries
library(stringr)
library(dplyr)
library(stats)
```

```{r}
##1. Potential PTCome
potential_PTCome=str_sub(EPM2A_potential$`Gene name:  EPM2A`, 4, 9)
potential_PTCome=gsub("\\D","", potential_PTCome)
potential_PTCome
potential_PTCome=as.integer(potential_PTCome)
potential_PTCome=na.omit(potential_PTCome)

EPM2A_potential

potential_PTCome #result
```

```{r}
##2. Cancer-associated PTCome
cancer_PTCome=PTEN_COSMIC[,6] #selection of the AA Mutation column
cancer_PTCome=str_sub(cancer_PTCome$`AA Mutation`, 4, 11) #extract the numeric fraction
cancer_PTCome <- data.frame (residues = c(cancer_PTCome))
count=table(cancer_PTCome$residues) #count of the number of mutations described in each residue (independently of the nucleotidic change)
cancer_PTCome=unique(cancer_PTCome) #select unique residues
df_cancer <-data.frame(count) #dataframe with unique PTC and the number of times they have been reported
df_cancer <- arrange(df_cancer, Var1) #PTC ordered by residue number
cancer_PTCome=as.integer(gsub("[:*:]","",df_cancer$Var1)) #extract the numeric fraction
cancer_PTCome=c(sort(cancer_PTCome))

cancer_PTCome #result
```

```{r}
#3. Germline-associated PTCome
germline_PTCome=PTEN_HGMD[,5] #select the protein change column
residues=c(germline_PTCome$...5)
str(residues)
residuo = c(residues)
nonsense <- grep("[:*:]",residues,value=T) #extraction of nonsense mutations
germline_PTCome=str_sub(nonsense, 4, 9)
germline_PTCome=as.integer(gsub("[:*:]","", germline_PTCome)) #extract the numeric fraction
germline_PTCome=unique(germline_PTCome)
germline_PTCome=na.omit(germline_PTCome)

germline_PTCome #result
```

```{r}
#4. Kernel density plot representation
gene_name <- "EPM2A"
protein_length <- 331

#cancer
cancer_100=((cancer_PTCome)*100)/ protein_length

cancer_100_neg=c(-(cancer_100))
cancer_100_pos=c(cancer_100_neg+200)
cancer_100_total=c(cancer_100,cancer_100_neg, cancer_100_pos)

#germline
germline_100=((germline_PTCome)*100)/ protein_length

germline_100_neg=c(-(germline_100))
germline_100_pos=c(germline_100_neg+200)
germline_100_total=c(germline_100, germline_100_neg, germline_100_pos)

#potential
potential_100=((potential_PTCome)*100)/ protein_length

potential_100_neg=c(-(potential_100))
potential_100_pos=c(potential_100_neg+200)
potential_100_total=c(potential_100, potential_100_neg, potential_100_pos)

#calculate densities
d_100_cancer=density(cancer_100_total)
d_100_potential=density(potential_100_total)
d_100_germline=density(germline_100_total)

#plot
plot(d_100_potential, main= gene_name, col="black", ylim=c(0,0.005), lwd=3.5, xlim=c(0,100))
lines(d_100_germline, col="blue", lwd=3.5)
lines(d_100_cancer, col="red", lwd=3.5)
```

